#!/usr/bin/env python3
"""Derive the witness and guard-ablation variants FROM property5.pv, so they cannot drift from it.

Two review findings produced this file. The witness used to be a checked-in copy of the model, so
deleting the honest emitter from the model alone left the copy certifying reachability that the model no
longer had: OF-3 again, with one file of separation. And the model's guard turned out not to be
load-bearing at all, which nothing tested, because no run ever removed just the guard.

Both variants are now generated from the model at verify time:

  property5_reachable.pv   same body, reachability query only. If the honest path dies, this reports the
                           event unreachable and the gate fails.
  property5_ablation.pv    same body with the spec 8.4 guard deleted and nothing else. If the guard is
                           not load-bearing, queries 2 and 3 stay true and the gate fails.

Usage: gen_variants.py <property5.pv> <out-dir>
"""
import re
import sys
from pathlib import Path

src_path, out_dir = Path(sys.argv[1]), Path(sys.argv[2])
src = src_path.read_text()
out_dir.mkdir(parents=True, exist_ok=True)

# --- witness: keep the body, replace the query block with a single reachability query --------------
i = src.index("(* 1. Every observed-action assertion")
j = src.index("\nprocess\n")
witness = src[:i] + '''(* GENERATED by gen_variants.py from property5.pv. Do not edit.

   Reachability witness: is the observed-action signing event reachable at all? ProVerif proves the
   negation of a reachability query, so the expected output is "RESULT not event(SignedObserved(...)) is
   false.", meaning a trace emitting it exists. A "true" here means the honest path is dead and every
   correspondence in property5.pv holds for the wrong reason. *)
query id: bitstring, subject: bitstring, digest: bitstring, policy: bitstring;
  event(SignedObserved(id, subject, digest, policy)).
''' + src[j:]
(out_dir / "property5_reachable.pv").write_text(witness)

# --- ablation: delete the spec 8.4 guard, change nothing else --------------------------------------
guard = re.search(
    r"  if t <> OBSERVED then\n  \(\n(?P<body>(?:.*\n)*?)  \)\.", src)
if not guard:
    sys.exit("gen_variants.py: could not find the spec 8.4 guard in property5.pv")
inner = "\n".join("  " + line[4:] if line.startswith("    ") else line
                  for line in guard.group("body").rstrip().split("\n"))
ablation = src[:guard.start()] + inner + ".\n" + src[guard.end():]
ablation = ablation.replace(
    "(* Q-SEAL section 16 property 5:",
    """(* GENERATED by gen_variants.py from property5.pv. Do not edit.

   GUARD ABLATION: the spec 8.4 guard on the host path is deleted and nothing else is changed. This is
   the one edit a real defect makes. Queries 2 and 3 MUST report false here. If they do not, the
   positive result in property5.pv does not depend on the guard it exists to enforce, which is exactly
   what an earlier version of this model got wrong.

   Q-SEAL section 16 property 5:""", 1)
(out_dir / "property5_ablation.pv").write_text(ablation)
print(f"generated property5_reachable.pv and property5_ablation.pv in {out_dir}")
