#!/usr/bin/env python3
"""Generate a Cryptol model + SAW script for evidence reassembly at a given fragment arity.

Property 6 is proved on the checked-in 4-fragment, 32-byte instance, which is small enough to read.
A deployed READ_EVIDENCE response is multi-kilobyte (an ML-DSA-44 signature alone is 2420 bytes), so
this emits a second instance at that scale from the same shapes, letting the same proof run at a size
nobody can dismiss as a toy. Both instances are checked by qseal/verify_evidence.sh.

Usage: gen_evidence_instance.py <frag-size> <num-frags> <out-dir>
"""
import os
import sys

FS, NF, OUT = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3]
EVID = FS * NF
name = f"QSEAL_Evidence_{FS}x{NF}"
os.makedirs(OUT, exist_ok=True)

src = open(os.path.join(os.path.dirname(__file__), "..", "model", "QSEAL_Evidence.cry")).read()
src = src.replace("module QSEAL_Evidence where", f"module {name} where")
src = src.replace("type FS   = 32", f"type FS   = {FS}")
src = src.replace("type NF   = 4", f"type NF   = {NF}")
src = src.replace("idxs = [0 .. 3]", f"idxs = [0 .. {NF - 1}]")
open(os.path.join(OUT, name + ".cry"), "w").write(src)

frags = "\n".join(f'    (sv{i}, c{i}) <- mk_frag "f{i}";' for i in range(NF))
svs = ", ".join(f"sv{i}" for i in range(NF))
cts = ", ".join(f"c{i}" for i in range(NF))
saw = f'''// GENERATED by qseal/proof/gen_evidence_instance.py -- do not edit. Evidence reassembly at the
// deployed fragment arity: {NF} fragments of {FS} bytes = {EVID} bytes, against the same C reference
// compiled with QSEAL_FRAG_SIZE={FS} and QSEAL_NUM_FRAGS={NF}. The readable {32}-byte 4-fragment
// instance lives in evidence.saw; this one exists so the result is not only a small-arity claim.
enable_experimental;

m <- llvm_load_module "{OUT}/evidence_{FS}x{NF}.bc";
import "{OUT}/{name}.cry";

let mk_frag nm = do {{
    seq   <- llvm_fresh_var (str_concat nm "_seq")   (llvm_int 8);
    total <- llvm_fresh_var (str_concat nm "_total") (llvm_int 8);
    dat   <- llvm_fresh_var (str_concat nm "_data")  (llvm_array {FS} (llvm_int 8));
    let sv = llvm_struct_value [llvm_term seq, llvm_term total, llvm_term dat];
    let ct = {{{{ {{ seq = seq, total = total, data = dat }} : Frag }}}};
    return (sv, ct);
}};

let reasm_spec = do {{
{frags}

    pfrags <- llvm_alloc_readonly (llvm_array {NF} (llvm_alias "struct.qseal_frag_t"));
    llvm_points_to pfrags (llvm_array_value [{svs}]);

    pout <- llvm_alloc (llvm_array {EVID} (llvm_int 8));
    llvm_execute_func [pfrags, pout];

    let fs = {{{{ [{cts}] : [{NF}]Frag }}}};
    llvm_points_to pout (llvm_term {{{{ (reassemble fs).evid }}}});
    llvm_return (llvm_term {{{{ if (reassemble fs).ok then (1 : [32]) else 0 }}}});
}};

reasm_ov <- llvm_verify m "qseal_evidence_reassemble" [] true reasm_spec z3;
print "VERIFIED: qseal_evidence_reassemble == Cryptol reassemble at {NF} fragments x {FS} bytes ({EVID} bytes)";

fails (llvm_verify m "qseal_evidence_reassemble_nocomplete" [] true reasm_spec z3);
print "MUTATION CAUGHT: the no-completeness-check variant is REJECTED at {NF} fragments x {FS} bytes";
'''
open(os.path.join(OUT, f"evidence_{FS}x{NF}.saw"), "w").write(saw)
print(f"generated {name}.cry and evidence_{FS}x{NF}.saw in {OUT}")
